set nu rnu hls is nosol ts=4 sw=4 ch=2 sc
filetype indent plugin on
syntax on

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" set termguicolors
colorscheme one
set background=dark
let g:one_allow_italics = 1

autocmd BufNewFile,BufRead * syntax keyword Repeat FOR REP FORD REPD
autocmd BufNewFile,BufRead * syntax keyword Type L VL VVL VI VVI II VII VVII VB VVB LD
autocmd BufNewFile,BufRead * syntax keyword Type vector tuple pair array deque set multiset unordered_set map unordered_map priority_queue
autocmd BufNewFile,BufRead * syntax keyword Constant D I nl inf inf_l cerr

call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
" set conceallevel=1
" let g:tex_conceal='abdmg'

Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

Plug 'editorconfig/editorconfig-vim'

Plug 'mattn/emmet-vim'

Plug 'jasonccox/vim-wayland-clipboard'

call plug#end()

